@baseUrl = http://localhost:3000

# RECADOS

### Lista todos os recados
GET {{ baseUrl }}/recados/
# ?limit=10
# &offset=10
# &user=Luis
### Lista um recado específico
GET {{ baseUrl }}/recados/2/

### Cria um novo recado
POST {{ baseUrl }}/recados/
Content-Type: application/json

{
  "texto": "NOVO recado",
  "de": "Joana",
  "para": "João"
}

### Atualiza um recado
PATCH  {{ baseUrl }}/recados/5/
Content-Type: application/json

{
  "texto": "4445 NOVO recado",
  "lido": true
}

### Deleta um recado
DELETE {{ baseUrl }}/recados/2/


# ---------

# PESSOAS

### Lista todas as pessoas
GET {{ baseUrl }}/pessoas/
# ?limit=10
# &offset=10
# &user=Luis
### Lista uma pessoa específica
GET {{ baseUrl }}/pessoas/2/

### Cria um nova pessoa
POST {{ baseUrl }}/pessoas/
Content-Type: application/json

{
  "password": "123456",
  "email": "luisitcho@gmail.com",
  "nome": "Joana"
}

### Atualiza um recado
PATCH  {{ baseUrl }}/pessoas/5/
Content-Type: application/json

{
  "texto": "4445 NOVO recado",
  "lido": true
}

### Deleta um recado
DELETE {{ baseUrl }}/pessoas/1/

# ---------


### AppControllerGetHello

# @name AppControllerGetHello
GET {{ baseUrl }}/home/hello/

### AppControllerGetExample

# @name AppControllerGetExample
GET {{ baseUrl }}/home/example/


### ConceitosManualController

# @name ConceitosManualControllerHome
GET {{ baseUrl }}/conceitos-manual/


### ConceitosAutomaticosControllerHome
# @name ConceitosAutomaticosControllerHome
GET {{ baseUrl }}/conceitos-automatico/